### ISSUE TITLE
Rename repository `daimler-foss` to `foss`

### ISSUE THREAD

**Issue by de-jcup** [mercedes-benz/foss#45]
## Situation
Currently FOSS projects of the Mercedes-Benz group do reference always https://github.com/mercedes-benz/daimler-foss.
(e.g. https://github.com/mercedes-benz/sechub/blob/develop/CONTRIBUTING.md does reference https://github.com/mercedes-benz/daimler-foss/blob/master/CODE_OF_CONDUCT.md)
But because of the rebranding we should avoid the term `daimler` - even in URLs.

## Wanted
The repository (and the URL) should not contain the name `daimler`

## Solution (suggestion)
1. Rename 
https://github.com/mercedes-benz/daimler-foss
to
https://github.com/mercedes-benz/foss
2. create a redirection from https://github.com/mercedes-benz/daimler-foss to https://github.com/mercedes-benz/foss
(if possible)
3. Inform MB foss projects about the change, so they can adopt.

**Comment by fafa0803** [comment]
Sorry guys, I was two weeks out of office.
I renamed the repository.
