### ISSUE TITLE
Update Daimler Protics

### ISSUE THREAD

**Issue by ceekai** [mercedes-benz/foss#49]
Please update "Daimler Protics" to Mercedes-Benz Tech Motion GmbH as this is our new company name since 01.04.22

https://www.mercedes-benz-tech-motion.com/legal/impressum.html

Mercedes-Benz Tech Motion GmbH
Gutenbergstraße 19
70771 Leinfelden-Echterdingen, Germany
Phone.: +497111759660
E-Mail: [info-tech-motion@mercedes-benz.com](mailto:info-tech-motion@mercedes-benz.com)

Sitz und Registergericht/Domicile and Register Court: Stuttgart, HRB-Nr./Commercial Register No.: 23635
Geschäftsführung/Management: Kai Fischer (CEO), Sascha Riegel (CFO)

https://www.daimler-protics.com/legal/impressum.html

**Comment by fafa0803** [comment]
@schr3gl3j Thank you 👍 .
@ceekai Thank you bringing this up. Feel yourself welcome to open a pull-request anytime :) .
Will be fixed with pr #51 .
